BASE_DATABASE_NAME = "mod_hyde/mod_hyde/AD-DB-"
COLLECTION_NAME = "ad-project"
# COLLECTION_NAME = "ad-project-small"
# COLLECTION_NAME = "ad-project-large"
EMBEDDING_MODEL = "text-embedding-3-small"
TOP_K = 5
OPENAI_MODEL_NAME = "gpt-3.5-turbo-0125"
HYDE_OPENAI_MODEL_NAME = "gpt-3.5-turbo-0125"
TOKENIZER_MODEL="distilbert/distilgpt2"